name: Mirror issues for brainstorming

on:
  issues:
    types:
      - reopened
      - opened
      - closed
      
jobs:
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: ${{ github.event.action == 'opened' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          gh issue create --title "$TITLE" --body "Mirrored from: jyasskin/test-design-reviews#$ISSUE_ID
          
          $ISSUE_BODY" --repo "jyasskin/test-design-reviews-private-brainstorming"

        env:
          TITLE: ${{ github.event.issue.title }}
          ISSUE_ID: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GH_TOKEN: ${{ secrets.PRIVATE_BRAINSTORMING_GITHUB_TOKEN }}
